### ISSUE TITLE
[Bug] Repeated load-unload of .dll libraries causes abrupt termination after exactly 533 cycles

### ISSUE THREAD

**Issue by FanDjango** [robinrodricks/FluentFTP.GnuTLS#100]
System: Windows 10. I have Not tested this under linux.
Current FluentFTP.GnuTLS 1.0.21

The following code **fails consistently** (on my machine) after **exactly 533** iterations:
```cs
		static void My_Loop_Test() {
			using (var client = new FtpClient("127.0.0.1", "mike", "7u8i9o0p")) {
				client.Config.EncryptionMode = FtpEncryptionMode.Explicit;
				client.Config.SslProtocols = SslProtocols.None;
				client.Config.DataConnectionType = FtpDataConnectionType.PASV;
				client.Config.DownloadDataType = FtpDataType.Binary;
				client.Config.ValidateAnyCertificate = true;
				client.Config.SslSessionLength = 0;

				client.Config.CustomStream = typeof(GnuTlsStream);
				client.Config.CustomStreamConfig = new GnuConfig() {
					SetALPNControlConnection = string.Empty,
					SetALPNDataConnection = string.Empty,
					DllUnloadByUseCount = true,
					LogLevel = 0,
					LogMessages = GnuMessage.None,
				};

				for (int i = 0; i < 999999; i++) {
					Console.WriteLine(i.ToString());
					client.Connect();
					client.Disconnect();
				}
			}
		}
```

What is the failure: No message, no indication in the log, nothing. Process terminates with code 3.

```
532
533

C:\Users\M....\Test_FluentZOS_Net_6.exe (process 30784) exited with code 3.
```

If I change the `DllUnloadByUseCount`  to `false`, there is no failure, even after many many load-unloads.

I will start investigating this.

@fredericDelaporte This is what is happening to you, I think.

**Comment by FanDjango** [comment]
@fredericDelaporte 533, once a minute is about 8 hours?

**Comment by fredericDelaporte** [comment]
Yes, it is about 8 hours. Still in my case it was not a stable time between failures, so not a stable count of init/deinit. Maybe there is some differences in the crash when the init/deinit is done in a loop doing nothing else without any wait time, and when it is done in an app actually using the FTP connection (calling `DownloadDirectory` once before closing) and waiting one minute before doing it again.

Anyway, that is great to have a good basis like your test, for investigating the trouble.

Exit code 3 : could be a C `abort` call according to this [blog](https://devblogs.microsoft.com/oldnewthing/20110519-00/?p=10623). So, that could be an explicit GnuTLS kill of the program, but in such case I would expect it to log something prior to that.

**Comment by FanDjango** [comment]
Well I'll be darned:

To find out that is causing the aboort, I decided to test the resiliency of `LoadLibrary(...)` and `FreeLibrary(...)` for loading `libgnutls-30.dll`. I haven't tested it yet for some other .dll to see if this is specific to the GNU library. 

The following code (.NET 6):

```cs
private const string dllNameWinUtil = @"Kernel32.dll";
[DllImport(dllNameWinUtil, CallingConvention = CallingConvention.StdCall, CharSet = CharSet.Ansi, SetLastError = true)]
private static extern IntPtr LoadLibrary([MarshalAs(UnmanagedType.LPStr)] string lpFileName);
[DllImport(dllNameWinUtil, CallingConvention = CallingConvention.StdCall, CharSet = CharSet.Ansi, SetLastError = true)]
[return: MarshalAs(UnmanagedType.Bool)]
private static extern bool FreeLibrary(IntPtr hModule);

static void my_Load_Unload_Test() {
	for (int i = 0; i < 6000; i++) {
		Console.WriteLine(i.ToString());

		// Load the .dll lib
		IntPtr dllP = LoadLibrary(@"libgnutls-30.dll");
		if (dllP == IntPtr.Zero) throw new Exception();

		// Unload the .dll lib
		bool result = FreeLibrary(dllP);
		if (!result) throw new Exception();
	}
}
```

run `my_Load_Unload_Test()` as a console app results in this:

```
...(1057 lines omitted)
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069

C:\Users\M....\Test_FluentZOS_Net_6.exe (process 7960) exited with code 3.
```

**Comment by FanDjango** [comment]
This is moving in the direction of analyzing the GnuTLS .dll library as to what it's DLLMAIN (if at all called or present) is doing, as well as any internal constructes they have somehow contrived - the compile is done with Mingw32 (windows port of gcc), there are many concerns out there about DLLMAIN related problems.

Other available GnuTSL .dll libraries, like the one supplied with FileZilla, also exhibit this behaviour.

**Need to test this under linux.**

**Perhaps it is best to just **not** do any unloading of the libraries.**

**Comment by FanDjango** [comment]
@Jojo-1000 We are back to square one re. your wanting the libraries freed if no-one is using them thanks to the problem desccribed above.

With the current code, there will be a `GlobalDeInit(...)` when use-count reaches zero, but freeing the libraries is currently commented out.

**Comment by Jojo-1000** [comment]
The interesting thing is that it is actually the `FreeLibrary` call that crashes.
When I run 1069 iterations of load/free dll, and then try to use FTPClient, the DLL loading fails with a proper error code:

> ERROR_DLL_INIT_FAILED
>
> 1114 (0x45A)
> ERROR_DLL_INIT_FAILED
>
> 1114 (0x45A)
>
> A dynamic link library (DLL) initialization routine failed.

Although setting the same error modes only using load/free does not do that, neither does just using the FTPClient repeatedly.
So my guess is that loading fails, but that is not detected for some reason, so the call to free crashes (and probably other uses of the library). This is strange, but I guess leaving the library loaded is not too bad for now. At least now it is not initialized all the time.
>
> A dynamic link library (DLL) initialization routine failed.

Although setting the same error modes only using load/free does not do that, neither does just using the FTPClient repeatedly.
So my guess is that loading fails, but that is not detected for some reason, so the call to free crashes (and probably other uses of the library). This is strange, but I guess leaving the library loaded is not too bad for now. At least now it is not initialized all the time.

**Comment by FanDjango** [comment]
> A dynamic link library (DLL) initialization routine failed.

The  DLLMAIN that is produced by vanilla Mingw32 gcc windows versions or whatever. It failed, they put to much stuff in there. If you google GnuTLS DLLMain you will see (old, 2014) discusssions about "doing away with Global Init" and instead "self initializing" the library. Who knows how far they went and whether it is Win compatible, as they seem to prefer the ELF side of these things at that time. Regardless, it is a question of whether the Win implementation of the dll DLLMAIN vie Mingw32 is correct for this task.

Big thanks for also trying this out. Isn't it nice / or strange that you get the same iterations before failure even on a different system?

**Comment by robinrodricks** [comment]
@FanDjango  can we just keep the DLL libs loaded and not unload them ever. Will that solve your problem? Is there a reason to unload the libs in the first place? I don't know much here so apologies but usually simpler solutions work better. Especially with native<->.NET interop.

**Comment by FanDjango** [comment]
Released to NuGet.

@robinrodricks 

> can we just keep the DLL libs loaded and not unload them ever

My response to that:

> With the current code, there will be a GlobalDeInit(...) when use-count reaches zero, but freeing the libraries is currently commented out.

**Comment by FanDjango** [comment]
Please let me add a few insights I gained over the past weeks on these issues: 

#40 
To make the code for linux viable and not use a lot of duplicated code, we stopped using DllImport and started loading the function delegates ourself with the help of LoadLibrary and FreeLibrary. It seemed "polite" to free the library after use. Nobody noticed the inherent flaw.

#88 
Making the library work in a multi-threaded environment meant moving GLobalDeInit and FreeLibrary into a usecount based environment. This didn't change the inherent flaw introduced long ago for #40.

(this one) #100
Finally, the problem reported already in #88, the failure after 8 hours, or after 533 FreeLibrary calls, surfaced, although it should have been reported many many weeks earlier as a separate topic. The user concerned just noticed in the course of the #88 resolution, that it was helping him also.

As usual, a number of things, mixed up together, have contributed to this evolution.

What remains though, is a numb feeling of despair:

libgnutls-30.dll, at least under windows, incorparates a number of internal schemes to facilitate its internal initialization, some of which was introduced quite long ago. At least under Windows .dll the design of this might be faulty and causes the DllMain feature to do things that are not totally compatible - you cannot Load/Unload this .dll as often as you like.

Is it worth it to search for the exact cause of this? To report it to the GnuTls people? I am hesitant as I feel they probably have bigger concerns. I myself do not currently have the resources to investigate both the source of GnuTls and the way the Mingw toolchain for compiling to windows might be making this happen.

Does repeated loading/unloading of libgnutls **also** fail under linux - then perhaps it would be worth reporting to them.

Another observation that makes disabling the FreeLibrary function a happy thing to do: The performance gain is actually quite noticable. Dynamic library unloading (= Free) is quite resource intensive. 

And with that, I will soon close this issue here before it gets too long. Any problems encountered with 1.0.22 should please be reported in a **new** issue.

**Comment by FanDjango** [comment]
@Jojo-1000 

Another interesting thing: The following code does **not** crash, it runs more or less for ever. The change is so abstruse that I don't consider this to be a viable solution, just a curiosity:

```cs
static void my_Load_Unload_Test() {
	for (int i = 0; i < 66000; i++) {
		Console.WriteLine(i.ToString());

		try {
			// Load the .dll lib
			IntPtr dllP = LoadLibrary(@"libgnutls-30.dll");
			if (dllP == IntPtr.Zero) throw new Exception();

			_ = LoadLibrary(@"libgnutls-30.dll");

			// Unload the .dll lib
			bool result = FreeLibrary(dllP);
					if (!result) throw new Exception();
			}

			catch (Exception e) {
				Console.WriteLine($"{e.Message}");
			}

	}
}
```

The **only** change: One additional LoadLibrary call, throwing away the returned pointer

**Comment by Jojo-1000** [comment]
@FanDjango
> The **only** change: One additional LoadLibrary call, throwing away the returned pointer

 I can kind of see why: Load library and Free library are also reference counted, so by loading twice you never actually unload the library.

For now I think it is best to just keep it loaded, especially if it is slow to free and someone uses many sequential connections. Maybe someone will figure out why this is broken in the future, maybe not. I think we can live with the small RAM overhead.
From what I can tell, `DllImport` would also not unload it after use.

**Comment by FanDjango** [comment]
Ooops, so now you see what happens when you loose focus and just play around. In my mainframe world, the additional load by the same TCB (task control block), here it would be thread, would not have counted. My bad.
