### ISSUE TITLE
GnuTlsCertificateSetX509SystemTrust causes GNUTLS_E_FILE_ERROR (-64) after sequentially loading provided DLLs on a Windows Azure Function 

### ISSUE THREAD

**Issue by rob-hendrickx-c4t** [robinrodricks/FluentFTP.GnuTLS#84]
# Extract from linked issue

@FanDjango 
Unfortunately looking at the logs of my test app, the polling loop that's being executed on a schedule now suddenly started throwing a different error over the "module could not be found" one after I loaded the DLLs in a sequence.

New error: 
> 'FluentFTP.GnuTLS.GnuTlsException: Error   : *GnuTlsCertificateSetX509SystemTrust(...) failed: (-64) GNUTLS_E_FILE_ERROR
   at FluentFTP.GnuTLS.Core.GnuUtils.Check(String methodName, Int32 result, Int32[] resultsAllowed)
   at FluentFTP.GnuTLS.GnuTlsInternalStream..ctor(String targetHostString, Socket socketDescriptor, CustomRemoteCertificateValidationCallback customRemoteCertificateValidation, X509CertificateCollection clientCertificates, String alpnString, GnuTlsInternalStream streamToResumeFrom, String priorityString, Boolean deInitGnuTls, String loadLibraryDllNamePrefix, Int32 handshakeTimeout, Int32 pollTimeout, GnuStreamLogCBFunc elog, Int32 logMaxLevel, GnuMessage logDebugInformationMessages, Int32 logQueueMaxSize)
   at FluentFTP.GnuTLS.GnuTlsStream.Init(BaseFtpClient client, String targetHost, Socket socket, CustomRemoteCertificateValidationCallback customRemoteCertificateValidation, Boolean isControl, IFtpStream controlConnStream, IFtpStreamConfig untypedConfig)
   at FluentFTP.FtpSocketStream.CreateCustomStream(String targetHost)
   at FluentFTP.FtpSocketStream.ActivateEncryptionAsync(String targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols, CancellationToken token)
   at FluentFTP.AsyncFtpClient.Connect(Boolean reConnect, CancellationToken token)
   at FluentFTP.AsyncFtpClient.Connect(CancellationToken token)

It never ends does it? 😅 Any clue what this one means/how it can be fixed? Or could it be because I now loaded the DLLs concurrently with the polling logic, where it would normally be executed beforehand and thus be nothing to worry about? (_not me being naive/hopeful_)

_Originally posted by @rob-hendrickx-c4t in https://github.com/robinrodricks/FluentFTP.GnuTLS/issues/76#issuecomment-1580803159_

**Comment by FanDjango** [comment]
For this one, I propose to do the following:

1. I will find out from the GnuTLS source, what `GnuTlsCertificateSetX509SystemTrust(...)` tries to do internally, to gain an understanding of what is going wrong here.

2. I need to know more about the context of this error - is it recurrring, is it recoverable, does it not happen with no parallelisation. Especially that last one. Once again maybe you would profit from locking - and then I would begin the search for possible culprits in the parallel execution of the `GnuTlsInternalStream`.

I assume this is once again under your Azure deployment/environment as you have described and have had so much trouble with in the previous issues.

**Comment by FanDjango** [comment]
> where it would normally be executed beforehand and thus be nothing to worry about?

Not sure that I understand this, but certainly the **first** usage of GnuTLS should not be significantly overlapped by the next usage if the load process is still underway in the first incarnation. Perhaps you could try to do a first initial "connect-disconnect" with no transfer on app start just to get everything initialised. If that helps, I can better understand the problem, mayhaps.

**Comment by rob-hendrickx-c4t** [comment]
@FanDjango In my local "unit test" I used earlier when investigating the concurrency issue, I cannot reproduce this issue. So I don't assume it is related to concurrency in this case unfortunately.

My test basically does the following:
* use an "external" directory as prefix, away from the app binaries
* delete any lib*.dll in the directory of the app binaries to fully reproduce the situation of the Azure Function on the DLL level
* use Task.WhenAll to do 5 concurrent create-connect-list-disconnect cycles

As an additional test to also validate it wouldn't behave differently on a concurrently executed Azure Function (which I doubt), I'll temporarily adapt my deployed test code to construct a client and do a connect-disconnect as you suggest in a lock before allowing any concurrent logic to be executed.

In the mean time I'm also updating to the latest version as I was still doing the "bulk load" myself on the older version, maybe there's a slight difference there after all

**Comment by rob-hendrickx-c4t** [comment]
@FanDjango Correct me if I'm wrong, but I guess the issue comes from a place that tries to add a certificate to the trusted store of the OS?
Can it be maybe that an Azure Function does not have permission to do so? In the source code of gnutls, I found the following in the add_system_trust method, which seems to be indirectly used by gnutls_certificate_set_x509_system_trust.

```
if (i == 0)
    store = CertOpenStore(CERT_STORE_PROV_SYSTEM, 0, 0, CERT_SYSTEM_STORE_CURRENT_USER , L"ROOT");
else
    store = CertOpenStore(CERT_STORE_PROV_SYSTEM, 0, 0, CERT_SYSTEM_STORE_CURRENT_USER, L"CA");

if (store == NULL)
    return GNUTLS_E_FILE_ERROR;
```

**Comment by FanDjango** [comment]
I'll make a release that skips this error - it will allow you continue. Either you then trust "any certificate" or it will fail.

What's failing is **loading** the certs from the store of trusted certs in the windows place where they are stored, so could be a mapping problem again.

**Comment by FanDjango** [comment]
Ok, released as **1.0.18**

That code place was actually meant to just produce an error message on "not successful". But I forgot to add in a list of failures to ignore (because I didn't know what failures to put in the list) - thus it terminates totally. No we know one failure we would like to ignore, at least :-) Mayby I will modify this later to ignore **all failures** and just produce an error message. Added to the TODO/INVESTIGATE list.

Try "validate any certificate" setting to true. Not meant as a permanent solution. Just want to see if there are **any other, more** suprises after that one, so that we can make a list, maybe, of what else turns up.

To really fix the failing "set_x509_system_trust" a lot more research must be done to find out wether that special azure environment you are using also remaps the location of this(these) file in that special directory.

**Comment by rob-hendrickx-c4t** [comment]
Hi @FanDjango 

I can confirm that everything now works as expected for this case (I already had validate any certificate enabled for communication with this development server). 

I applied the logging settings you shared but I don't seem to see them. I only see other logs from FluentFTP itself.

See them attached (note that some duplication exists due to concurrency)
[query_data.csv](https://github.com/robinrodricks/FluentFTP.GnuTLS/files/11688416/query_data.csv)

**Comment by FanDjango** [comment]
GnuTLS stuff **all** comes as "verbose"

**Comment by rob-hendrickx-c4t** [comment]
Yes, but Verbose is mapped to Debug in my log adapter..

**Comment by FanDjango** [comment]
> To really fix the failing "set_x509_system_trust" a lot more research must be done to find out wether that special azure environment you are using also remaps the location of this(these) file in that special directory.

Under Windows, it's not a file - it turns out that this function will enteran Win32 API function call "CertOpenStore". Which then fails.

Anyway, I have modified the code further to implement the following:
> Maybe I will modify this later to ignore all failures and just produce an error message
